### ISSUE TITLE
Calculators are great but...

### ISSUE THREAD

**Issue by massimocode** [SMH110/widgets#35]
Calculators are great and our users love them but I think we could offer our users so much more! If we remade our calculator to be a widget then we could add some more widgets, like a weather widget (allows you to enter your location and it will tell you the weather), a notes widget, maybe a currency converter widget and a translator widget. Users can add widgets onto their screen according to what they find useful. We could rename this repository to Cool-Widgets. Soon we'll be making millions! What do you think?

**Comment by SMH110** [comment]
I start working on this issue
https://github.com/SMH110/My-Calculator/commit/1ffe60e53e27454a6fb124fde6adfa5171ae2d7d

**Comment by SMH110** [comment]
Have look here Please https://github.com/SMH110/My-Calculator/commit/a59db08dfde91ec43fadf1d3000ff1fb8d38cf6f

**Comment by SMH110** [comment]
Now have a look on https://github.com/SMH110/My-Calculator/commit/81577819cc5f2a57625b197a7da9642b0d595a76

**Comment by massimocode** [comment]
Functionally it works but there's no way to tell if a task has been done or not. Tasks which are marked as done should be highlighted green

**Comment by massimocode** [comment]
I've added a new issue for the todo list. Let's continue discussing the todo list over there. We'll keep this issue open until we create other issues for the things mentioned here (i.e. weather widget, adding/removing widgets, renaming repo, etc)
