### ISSUE TITLE
Add todo list widget

### ISSUE THREAD

**Issue by massimocode** [SMH110/widgets#39]
As discussed in https://github.com/SMH110/My-Calculator/issues/35

**Comment by SMH110** [comment]
Now it's green in https://github.com/SMH110/My-Calculator/commit/22335cecdc07c2f980e34bbe8335ac046216131b

**Comment by SMH110** [comment]
Code review changes
https://github.com/SMH110/My-Calculator/commit/8fffb479c03a43f8f91b658a67c38c98bacd2085

**Comment by massimocode** [comment]
Merged
