### ISSUE TITLE
HTML is getting difficult to maintain

### ISSUE THREAD

**Issue by massimocode** [SMH110/widgets#41]
I'm looking at the widget branch which will add the todo list and I think the HTML is getting difficult to maintain. It's not nice to have the HTML for the calculator and the todo list in one place.

I think we should look at using Knockout components. This way, the HTML for the calculator and todo list can be separate from the main page and even loaded dynamically using Require JS.

**Comment by SMH110** [comment]
I have tried to do that but it didn't work
https://github.com/SMH110/My-Calculator/commit/af350dcd40ac752066e529fb59155243221f81be

**Comment by massimocode** [comment]
`I think we should look at using Knockout components.`

http://knockoutjs.com/documentation/component-overview.html

**Comment by SMH110** [comment]
This 
`html: calculatorHtml.calcHtmlCode 
didn't work
`https://github.com/SMH110/widgets-/commit/5f996d83e8f752338353851f77057bc03eead608

**Comment by massimocode** [comment]
That's correct, because the HTML has been rendered but data-bind attributes within the HTML were ignored.

We should be looking at using knockout components instead. I'll see if I can put in a PR for it.

**Comment by massimocode** [comment]
I've created a PR for this here https://github.com/SMH110/widgets/pull/48. Please checkout the updated readme.

**Comment by massimocode** [comment]
The PR converts the calculator to a widget. Feel free to go ahead and checkout the branch and convert the todo list to a widget as well.

**Comment by SMH110** [comment]
Done here 43e800d
