### ISSUE TITLE
Split up CSS

### ISSUE THREAD

**Issue by massimocode** [SMH110/widgets#42]
I am looking at the code for the latest todo list and noticed that we now have a styles.css file which not only has styles for the whole page, but also styles for the calculator and styles for the todo list.

I think we should have a calculator.css file and a todo-list.css file, and them `@import` them into the styles.css file.

**Comment by SMH110** [comment]
Done in https://github.com/SMH110/My-Calculator/commit/b190e13e819e649006e399b75c4029214d1b2599

**Comment by massimocode** [comment]
Merged
