### ISSUE TITLE
Add / Remove widgets

### ISSUE THREAD

**Issue by massimocode** [SMH110/widgets#44]
After we merge the todo list, I was thinking we should add some more functionality to the App to allow users to Add/Remove calculators and todo lists. I know we currently have the todo list as taking up the right 1/3rd of the screen, but it would be good if we could have buttons like "Add Calculator" and "Add To Do List" and let the user decide what they want on their screen. Each widget would have a button to remove itself. Each widget would be the same size as well.

**Comment by massimocode** [comment]
I just wanted to clarify that you should be able to add multiple todo lists

**Comment by SMH110** [comment]
Done in  https://github.com/SMH110/widgets/commit/63f5453d3811e7f755cbcc3d183694f442168bc9

**Comment by SMH110** [comment]
have look here
https://github.com/SMH110/widgets/commit/3055113ea310f6c9893b492f1cfeb57641a14798

**Comment by SMH110** [comment]
Now have look 
https://github.com/SMH110/widgets/commit/b08f50556b6b813934ab7cb72593178dc8ec1049

**Comment by massimocode** [comment]
I am going to merge this and create another issue for not being able to control whether the todo list is added first or the calculator (i.e. control the order they appear on the screen)
