### ISSUE TITLE
Add weather widget

### ISSUE THREAD

**Issue by massimocode** [SMH110/widgets#46]
I think we should create a new widget that allows the user to enter their location, and then we will display the current weather for their location to them.

**Comment by massimocode** [comment]
Of course we can't make up the results and they can't be calculated on the client side, so we are going to need to find some kind of weather API we can use to query to get the weather data for the user's location.

**Comment by SMH110** [comment]
Have look https://github.com/SMH110/widgets/commit/2a39fc832c6da43d37a16c352fe838ec26e37999 Please

**Comment by SMH110** [comment]
Fixed the bug when the API respond with not a Json body 
https://github.com/SMH110/widgets/commit/b50115865192ebe6579f9143914c4b6ba1574c69

**Comment by SMH110** [comment]
Merged https://github.com/SMH110/widgets/pull/56
