### ISSUE TITLE
Add translator widget

### ISSUE THREAD

**Issue by massimocode** [SMH110/widgets#50]
I think we should add a translator widget similar to http://translate.google.com where a user can select a source and destination language and enter some text, and the text will be translated.

**Comment by SMH110** [comment]
Have look here https://github.com/SMH110/widgets/commit/7eabc9508521f20a35feff48211fcc626ae0eaa9

Please

**Comment by SMH110** [comment]
PR: https://github.com/SMH110/widgets/pull/58

**Comment by SMH110** [comment]
Have look please on the this https://github.com/SMH110/widgets/commit/5f25a1167c25b0e0bd62813a3394bf2fa3f53f10
I didn't finish of fixing the html of translate yet, I just wrote some tests for translate.js

**Comment by SMH110** [comment]
I think I have done from the translate widget
https://github.com/SMH110/widgets/pull/58/commits/683c6a421364c90cabfc7b5daab8c702b3f5870e

**Comment by SMH110** [comment]
Have look https://github.com/SMH110/widgets/commit/09d4c2add7b8569743d80731f73dbe53edfc0686
and https://github.com/SMH110/widgets/commit/7c4829120821b5c9be0b3833f48969a6bb46cb2d

**Comment by SMH110** [comment]
Merged https://github.com/SMH110/widgets/pull/58
