### ISSUE TITLE
Convert project to TypeScript

### ISSUE THREAD

**Issue by massimocode** [SMH110/widgets#51]
I think that as the project grows larger, it would be beneficial for us to switch over to TypeScript so that we can have static analysis on the codebase.

It would also allow us to safely use ES6 constructs and have them compiled down to ES5 (so that they work in all current browsers) and also would allow us to use ES6 import/export syntax and have them compiled down to AMD/CommonJS (i.e. UMD).

**Comment by SMH110** [comment]
Have look here please https://github.com/SMH110/widgets/commit/8cb42b057e2fdd10c79b971009e61e99749217a6

**Comment by SMH110** [comment]
https://github.com/SMH110/widgets/commit/4840db1c9fcf53aa38180aed0e7a82beded5280e

**Comment by SMH110** [comment]
Merged https://github.com/SMH110/widgets/pull/60
