### ISSUE TITLE
Allow users to pick ordering of widgets and ensure they are the same size

### ISSUE THREAD

**Issue by massimocode** [SMH110/widgets#53]
I'm currently unable to post screenshots but I will email you some.

Several issues:
1) Remove calculator button size is not consistent with other buttons
2) Only 2 widgets on a large monitor, we should really allow 4 on large, 3 on medium, 2 on small (we used to allow 4 calculators!)
3) Can't put todo list after calculator
4) Todo lists only on the left and calculators only on the right, so we're not making good use of screen space if the user has 1 todo list and 5 calculators. And it's even worse when the user doesn't want any todo lists!

**Comment by SMH110** [comment]
I tried to fix the remove button size 
https://github.com/SMH110/widgets/commit/7a7e00c708a5c03735a7e3a6c0a70411c38a4270

but the other problem that when you add different calculators with to do list 
they don't the space very well; I didn't know how to fix this

**Comment by massimocode** [comment]
@SMH110 Please review https://github.com/SMH110/widgets/pull/55 and merge and close this issue when ready and tested.
